#!/usr/bin/env zsh
# =====================================================================
# compile_csv2_linux.zsh — build csv2 as a Linux ELF, natively, wherever it
#                          is run: the aarch64 guest VM or WSL2 on x86_64.
# compile_csv2_linux.zsh — 在它被執行的地方原生建置 csv2 成 Linux ELF：aarch64 的
#                          guest VM，或 x86_64 上的 WSL2。
#
# LA. It said "aarch64" here and in its banner, and it is run on WSL2 too, so
# on that node it announced an architecture it was not building for -- while
# `file` two lines from the end printed the truth. Nothing broke; a reader of
# the four-node matrix simply attributed the result to the wrong node. There is
# no architecture-specific step in this script: no target triple, no arch flag.
# LA。這裡與它的橫幅都寫著 "aarch64"，而它同時也在 WSL2 上執行，於是在那個節點上它宣告了一個
# 自己並沒有在建置的架構——同時結尾前兩行的 `file` 印出的是真相。沒有東西壞掉；只是讀四節點
# 矩陣的人會把結果歸給錯的節點。這支腳本裡沒有任何架構專屬的步驟：沒有 target triple、沒有
# 架構旗標。
#
# Kept separate from the auto-detecting compile_csv2.zsh because the guest
# requires an explicit toolchain and source location. They otherwise differ
# in exactly one place -- where swiftc lives -- and that is the
# whole point of csv2 having no C dependencies: swift_tar needs a sysroot,
# generated module maps and zlib headers for its Linux build, and csv2
# needs none of it. Foundation and Dispatch only.
# 與自動偵測平台的 compile_csv2.zsh 分開，因為 guest 必須明確指定 toolchain 與
# 原始碼位置。除此之外兩者只差一處——swiftc 在哪裡——
# 而這正是「csv2 沒有 C 依賴」的價值所在：swift_tar 的 Linux 建置需要 sysroot、
# 自行產生的 module map 與 zlib header，csv2 一樣都不需要，只用 Foundation
# 與 Dispatch。
#
# Expected in the guest / guest 內預期存在：
#   /workspace/opt/swift/usr/bin/swiftc    Swift toolchain
#   /workspace/csv2/src/*.swift            source, injected by the host driver
#
# Output / 輸出：$SRC_DIR/release/csv2  (a native Linux ELF / 原生 Linux ELF)
#
# Usage / 用法：
#   zsh /workspace/csv2/compile_csv2_linux.zsh
#   SRC_DIR=/elsewhere zsh compile_csv2_linux.zsh
# =====================================================================
set -eu

SWIFT_PREFIX=${SWIFT_PREFIX:-/workspace/opt/swift/usr}
SRC_DIR=${SRC_DIR:-/workspace/csv2}
SWIFTC="$SWIFT_PREFIX/bin/swiftc"

die() { print -u2 -- "compile_csv2_linux: $*"; exit 1 }

[[ -x "$SWIFTC" ]] || die "swiftc not found at $SWIFTC / 找不到 swiftc：$SWIFTC"
[[ -d "$SRC_DIR/src" ]] || die "source not found at $SRC_DIR/src / 找不到原始碼：$SRC_DIR/src"

cd "$SRC_DIR"

OPT="-O"
for arg in "$@"; do
    case "$arg" in
        --debug) OPT="-Onone" ;;
        *) die "unknown option: $arg / 未知選項：$arg" ;;
    esac
done

# The build identity, produced the same way the macOS script produces it and
# before the list that names it is validated. In the guest there is no .git --
# the source arrives as a tar payload -- so this says `unknown`, which is a
# true statement about that build rather than a guess. The version string is
# still able to say "this is not the same build as that one", which is the
# question it exists to answer.
# 這次建置的身分，與 macOS 那支腳本以同樣方式產生，並且在「指名它的那份清單」被檢驗之前。
# guest 上沒有 .git——原始碼是以 tar payload 送進去的——因此這裡會說 `unknown`，那是關於那次建置
# 的一句真話，而不是猜測。版本字串仍然說得出「這不是那一個建置」，而那正是它存在所要回答的問題。
build_id=$(git -C "$SRC_DIR" describe --always --dirty 2>/dev/null) || build_id=""
[[ -n $build_id ]] || build_id=unknown
print -r -- "// Generated by the build. Not in git: it changes with every commit." > "$SRC_DIR/src/BuildInfo.swift"
print -r -- "// 由建置產生。不進 git：它每個 commit 都會變。" >> "$SRC_DIR/src/BuildInfo.swift"
print -r -- "let CSV2_BUILD = \"$build_id\"" >> "$SRC_DIR/src/BuildInfo.swift"

# One list, read from src/sources.list -- see the reasoning in that file.
# 只有一份清單，讀自 src/sources.list——理由寫在該檔中。
SOURCES=(${(f)"$(grep -v '^[[:space:]]*#' src/sources.list | grep -v '^[[:space:]]*$')"})
[[ ${#SOURCES} -gt 0 ]] || { print -u2 -- "src/sources.list is empty / src/sources.list 是空的"; exit 1 }

for f in $SOURCES; do
    [[ -f "$f" ]] || die "missing source: $f / 缺少原始檔：$f"
done

mkdir -p release

# Say what was MEASURED, not what was assumed. See LA at the top.
# 說出**量到**的，而不是假設的。見檔首的 LA。
HOST_UNAME=$(uname -sm)
print -- "Building csv2 for $HOST_UNAME ($OPT) / 正在為 $HOST_UNAME 建置 csv2（$OPT）"
"$SWIFTC" -swift-version 6 -warnings-as-errors $OPT -o release/csv2 $SOURCES

# Verify by RUNNING it, not by checking the file exists -- the same rule the
# macOS build follows. Here it also proves the Swift runtime resolves: a binary
# that links but cannot find libswiftCore at run time is the exact failure
# swift_tar hit with libxml2, and it is invisible until something runs it.
# 以執行來驗證，而非檢查檔案存在——與 macOS 版同一條規則。在這裡它還額外證明
# Swift runtime 解析得到：一個「連結成功但執行時找不到 libswiftCore」的執行檔，
# 正是 swift_tar 在 libxml2 上踩過的失敗，而它在真的被執行之前完全看不見。
./release/csv2 --version >/dev/null
print -- "OK: $(./release/csv2 --version) -> $SRC_DIR/release/csv2"
file release/csv2 2>/dev/null || true
